---
title: "Interventions Guide"
author: "Anne Stahlfeld & Tobias Holden"
date: "`r Sys.Date()`"
output: html_document
---

## Drug-Based Interventions

### Case management

Case management is controlled in EMOD by an [`add_treatment_seeking()`](https://github.com/numalariamodeling/emodpy-malaria/blob/main/emodpy_malaria/interventions/treatment_seeking.py) function within emodpy-malaria. This function is a node level intervention that allows you to target individuals on the node for malaria treatment through health seeking behavior. 

In this example, treatment is triggered by a new clinical case and codes for differences in case management coverage between individuals of age 0-5 yrs and 5-100yrs as set by the two trigger dictionaries' respective `agemin` and `agemax`. `Seek` dictates the proportion of people who will seek care with a new clinical case - it is usually set to 1 such that `coverage` is the true case management coverage level. `Rate` represents how quickly the case will receive treatment. It is used to create an exponential distribution of the delay period. We usually set `rate = 1/3` for clinical cases and `rate = 1/2.` for severe cases.

You can also specify which drugs are used for case management. The default is Artemether-Lumefantrine with age-based dosing. 

Additional parameters can be added to restrict case management to certain nodes, node properties, or individual properties. See [here](https://docs.idmod.org/projects/emodpy-malaria/en/latest/emodpy_malaria.interventions.treatment_seeking.html) for more information.


```{python,eval=F}
import emod_api.campaign as camp
import emodpy_malaria.interventions.treatment_seeking as cm

cm.add_treatment_seeking(camp, start_day=0, drug=['Artemether', 'Lumefantrine'],
                         targets=[{'trigger': 'NewClinicalCase', 
                                   'coverage': 0.7, 'agemin': 0, 'agemax': 5,
                                   'seek': 1,'rate': 0.3},
                                 {'trigger': 'NewClinicalCase', 
                                  'coverage': 0.5, 'agemin': 5, 'agemax': 100,
                                  'seek': 1,'rate': 0.3},
                                 {'trigger': 'NewSevereCase', 
                                  'coverage': 0.85, 'agemin': 0, 'agemax': 100,
                                  'seek': 1,'rate': 0.5}],
                         broadcast_event_name="Received_Treatment")
```

### Drug Campaigns

Using [`add_drug_campaign()`](https://github.com/numalariamodeling/emodpy-malaria/blob/main/emodpy_malaria/interventions/drug_campaign.py) you can set different drug campaigns including MDA, MSAT, SMC, fMDA, MTAT, rfMSAT, and rfMDA. This function also includes the ability to set coverage levels, repetitions (such as SMC cycles) and the timesteps between them, diagnostics information for campaigns that include testing, target groups, and restrictions on who can receive drugs by node or individual properties. Node and individual properties are set in the demographics file and can be called upon here for things like low vs high access groups (see drug IP example **link**).

This example details an SMC intervention. Timesteps between repetitions (if more than one cycle given) is set to 30 days as SMC is given on a monthly basis during peak season. The target group is also specified here to limit the age group to 0.25-5 year old children. This example uses adherent drug configurations as previously shown.

```{python,eval=F}
import emod_api.campaign as campaign
import emodpy_malaria.interventions.drug_campaign as drug_campaign

drug_campaign.add_drug_campaign(campaign, 
                                campaign_type="SMC", 
                                start_days=[165], 
                                drug_code="SPA", #single code if not using adherent drug
                                #adherent_drug_configs=[adherent_drug], #use adherent drug in next how to
                                repetitions=4, 
                                tsteps_btwn_repetitions=30, 
                                coverage=0.7,
                                target_group={'agemin': 0.25, 'agemax': 5},
                                receiving_drugs_event_name="Received_SMC")                       
```

For more details on all of the campaign types and other options, checkout the [emodpy-malaria documentation](https://docs.idmod.org/projects/emodpy-malaria/en/latest/emodpy_malaria.interventions.drug_campaign.html#emodpy_malaria.interventions.drug_campaign.add_drug_campaign)

### Change Drug Adherence

Adherence to drugs can be modified using [`adherent_drug`](https://github.com/numalariamodeling/emodpy-malaria/blob/main/emodpy_malaria/interventions/adherentdrug.py). This allows you to detail doses (and drugs given), intervals between doses, actual adherence values, and more. More documentation on how to configure adherent drugs is [here](https://docs.idmod.org/projects/emod-malaria/en/latest/parameter-campaign-individual-adherentdrug.html) and the specifics of the function [here](https://docs.idmod.org/projects/emodpy-malaria/en/latest/emodpy_malaria.interventions.adherentdrug.html).

Configuring adherence is not required. In the absence of specific configuration, adherence to the full treatment course is assumed to be 100%.

```{python, eval=F}
import emod_api.campaign as campaign
import emodpy_malaria.interventions.drug_campaign as drug_campaign
import emodpy_malaria.interventions.adherentdrug as ad
adherent_drug = ad.adherent_drug(campaign=campaign,
                                     doses=[["Sulfadoxine", "Pyrimethamine", 'Amodiaquine'],
                                            ['Amodiaquine'],
                                            ['Amodiaquine']],
                                     dose_interval=1,
                                     non_adherence_options=['Stop'],
                                     non_adherence_distribution=[1],
                                     adherence_values=[
                                         1,    # for day 1
                                         0.6,  # day 2
                                         0.4   # day 3
                                     ]
                                     )
```

## Diagnostic Surveys

[Diagnostic surveys](https://github.com/numalariamodeling/emodpy-malaria/blob/main/emodpy_malaria/interventions/diag_survey.py) are useful interventions for triggering events based on an individual's diagnosis. Testing can be performed at regular intervals (`tsteps_between_repetitions`) for a set number of `repetitions` based on `target` groups and `coverage`. Testing can also be triggered by other events, such as receiving a particular dose of PMC in this example.

Different methods of diagnostic testing may also be utilized, including *TRUE_PARASITE_DENSITY*, *BLOOD_SMEAR*, *PCR*, *PF_HRP2*, *TRUE_INFECTION_STATUS*, and *HAS_FEVER*. Diagnostic threshold, sensitivity, and specificity can all be parameterized. Once a positive or negative result is obtained in the simulation, the relative configs parameter dictates what will happen to that individual. In this example, either diagnosis broadcasts an event for that individual that they were positive or negative on the day that they received their first dose of PMC.

```{python,eval=F}
import emod_api.campaign as campaign
import emodpy_malaria.interventions.diag_survey as diagnostic_survey
import emod_api.interventions.common

parasites_detected = emod_api.interventions.common.BroadcastEvent(campaign, Event_Trigger="Day_0_positive")
no_parasites_detected = emod_api.interventions.common.BroadcastEvent(campaign, Event_Trigger="Day_0_negative")

diagnostic_survey.add_diagnostic_survey(campaign=campaign, start_day=0, 
                                        diagnostic_type="TRUE_PARASITE_DENSITY",
                                        diagnostic_threshold=20,
                                        trigger_condition_list=['Received_PMC_1'],
                                        positive_diagnosis_configs=[parasites_detected],
                                        negative_diagnosis_configs=[no_parasites_detectedc])
```

Additional targeting and configuration parameters are described [here](https://docs.idmod.org/projects/emodpy-malaria/en/latest/emodpy_malaria.interventions.diag_survey.html)

## Vaccination

### RTS,S

## Vector Control

### Bednets

Insecticide-treated bednets can be distributed with the `add_itn_scheduled()` function, which has many options to configure who is targeted for ITN distribution and the properties of the insecticides used.

```{python,eval=F}
import emod_api.campaign as campaign
from emodpy_malaria.interventions.bednet import add_itn_scheduled
add_itn_scheduled(campaign,
        start=365, # starts on first day of second year
        coverage_by_ages=[
          {"coverage":1,"min": 0, "max": 10},     # 100% for 0-10 years old
          {"coverage":0.75,"min": 10, "max": 50}, # 75% for 10-50 years old
          {"coverage":0.6,"min": 50, "max": 125}  # 60% for everyone else
        ],
        repetitions=5, # ITN will be distributed 5 times
        timesteps_between_repetitions= 365*3 # three years between ITN distributions
)

# Full Argument List : 

def add_itn_scheduled(campaign,
                      start_day: int = 0,
                      coverage_by_ages: list = None,
                      demographic_coverage: float = 1.0,
                      target_num_individuals: int = None,
                      node_ids: list = None,
                      repetitions: int = 1,
                      timesteps_between_repetitions: int = 365,
                      ind_property_restrictions: list = None,
                      receiving_itn_broadcast_event: str = None,
                      blocking_initial_effect: float = 0.9,              # NOTE: these default effect sizes and kinetics are not calibrated values
                      blocking_box_duration: float = 0,
                      blocking_decay_time_constant: float = 7300,
                      killing_initial_effect: float = 0.6,
                      killing_box_duration: int = 0,
                      killing_decay_time_constant: float = 7300,
                      repelling_initial_effect: float = 0,
                      repelling_box_duration: float = -1,
                      repelling_decay_time_constant: float = 0,
                      usage_initial_effect: float = 1,
                      usage_box_duration: float = -1,
                      usage_decay_time_constant: float = 0,
                      insecticide: str = "",
                      cost: float = 0,
                      intervention_name: str = "SimpleBednet")
```

The default `coverage_by_age` sets coverage to 100% for everyone regardless of age.

### Indoor Residual Spraying (IRS)

Insecticide-treated bednets can be distributed with the `add_scheduled_irs_housing_modificatoin()` function, which has many options to configure the effects of insecticides used.

```{python, eval=F}
import emod_api.campaign as campaign
from emodpy_malaria.interventions.irs import add_scheduled_irs_housing_modification

add_scheduled_irs_housing_modification(campaign, 
                                       start_day = 1,
                                       demographic_coverage = 1, 
                                       killing_initial_effect = 1,                    # NOTE: these default effect sizes and kinetics are not calibrated values
                                       killing_box_duration = 0,
                                       killing_decay_time_constant = 90,
                                       repelling_initial_effect = 0,
                                       repelling_box_duration = 0,
                                       repelling_decay_time_constant = 90,
                                       insecticide = "",
                                       intervention_name = "IRSHousingModification"
    """
        Adds scheduled IRSHousingModification intervention to the campaign. The IRSHousingModification intervention class
        includes Indoor Residual Spraying (IRS) in the simulation. IRS is another key vector control tool in which
        insecticide is sprayed on the interior walls of a house so that mosquitoes resting on the walls after
        consuming a blood meal will die. IRS can also have a repellent effect. Because this class is distributed
        to individuals, it can target subgroups of the population. To target all individuals in a node, use
        IndoorSpaceSpraying. Do not use IRSHousingModification and IndoorSpaceSpraying together.

    Args:
        campaign: A campaign builder that also contains schema_path parameters
        start_day: The day on which the intervention is distributed
        demographic_coverage: The fraction of individuals in the target demographic that will receive this intervention
        node_ids: A list of node ids to which this intervention will be distributed. None or [] distributes
            intervention to all nodes
        killing_initial_effect: Initial strength of the Killing effect. The effect may decay over time.
        killing_box_duration: Box duration of effect in days before the decay of Killing Initial_Effect.
        killing_decay_time_constant: The exponential decay length, in days of the Killing Initial_Effect.
        repelling_initial_effect: Initial strength of the Killing effect. The effect decays over time.
        repelling_box_duration: Box duration of effect in days before the decay of Repelling Initial Effect.
        repelling_decay_time_constant: The exponential decay length, in days of the Repelling Initial Effect.
        insecticide:The name of the insecticide defined in config.Insecticides for this intervention.
            If insecticides are being used, then this must be defined as one of those values.  If they are not
            being used, then this does not needed to be specified or can be empty string.  It cannot have a
            value if config.Insecticides does not define anything.
        intervention_name: The optional name used to refer to this intervention as a means to differentiate it from
            others that use the same class. It’s possible to have multiple IRSHousingModification interventions
            attached to a person if they have different Intervention_Name values.

    Returns:
        Nothing
    """

```

### Larvicides
