---
title: "Individual Properties Guide"
author: "Anne Stahlfeld & Tobias Holden"
date: "`r Sys.Date()`"
output: html_document
---

## Adding to Demographics

Individual properties, possible property values, and initial distributions of property values must be specified in the demographics file.

In this example we create a study cohort where 50% of individuals are assigned to 'Placebo' and the other 50% are assigned to 'Treatment' without any transitions between the groups or differences in transmission by group. We add this property set directly to the basic demographics item. This example includes only one property but you can define as many as needed.

```{python,eval=F}
import emodpy_malaria.demographics.MalariaDemographics as Demographics
def build_demog():

    demog = Demographics.from_template_node(lat=1, lon=2, pop=1000, name="Example_Site")
    demog.SetEquilibriumVitalDynamics()
    
    age_distribution = Distributions.AgeDistribution_SSAfrica
    demog.SetAgeDistribution(age_distribution)
    
    initial_distribution = [0.5, 0.5]
    demog.AddIndividualPropertyAndHINT(Property="StudyCohort", Values=["Placebo", "Treatment"],
                                       InitialDistribution=initial_distribution)              
    return demog
```

## Using in Interventions

Most interventions can be targeted to individuals holding specific IP values, typically with the `ind_property_restrictions` function argument and setting the desired Individual Property restrictions. This example creates an SMC drug campaign that is limited to individuals in the 'Treatment' group as defined in the demographics file.

```{python,eval=F}
import emod_api.campaign as campaign
import emodpy_malaria.interventions.drug_campaign as drug_campaign

drug_campaign.add_drug_campaign(campaign, 
                                campaign_type="SMC", 
                                start_days=[165], 
                                drug_code="SPA",
                                repetitions=4, 
                                tsteps_btwn_repetitions=30, 
                                coverage=0.7,
                                ind_property_restrictions=[{'StudyCohort': 'Treatment'}],
                                target_group={'agemin': 0.25, 'agemax': 5},
                                receiving_drugs_event_name="Received_SMC")                  
```

## Using in Reporting

Individual properties can also be used in reporting to limit the report to only those individuals in the specified group, to track the number of individuals with an IP or combination of IPs, or to report the IPs of individuals.

### Malaria Summary Report

For the [`MalariaSummaryReport`](https://docs.idmod.org/projects/emod-malaria/en/latest/software-report-malaria-summary.html), aggregation can be restricted by IP using the `ipfilter` argument. For example, the following function will report, on aggregate, every 30 days on new infections and other infection updates in the Placebo group across the three age bins.

```{python,eval=F}
from emodpy_malaria.reporters.builtin import *
add_malaria_summary_report(task, manifest, 
                           start_day=1, 
                           end_day=sim_years*365, 
                           reporting_interval=30,
                           age_bins=[0.25, 5, 115],
                           must_have_ip_key_value='StudyCohort:Placebo',
                           filename_suffix='_placebo',
                           pretty_format=True)
```

### Property Report

The [`PropertyReport`](https://docs.idmod.org/projects/emod-malaria/en/latest/software-report-property.html) outputs select channels (population, infected, new infections, and disease deaths) for all combinations of IPs and IP values. This output can get very large if there are many IPs and/or IP values in play.

To request the `PropertyReport`:

```{python,eval=F}
# add to config parameter setup
config.parameters.Enable_Property_Output = 1
```

### Node Demographics Report

The [`NodeDemographicsReport`](https://docs.idmod.org/projects/emod-malaria/en/latest/software-report-malaria-node-demographics.html) reports on node-level counts of individuals by age bin, infection status, and IPs if requested through `IP_key_to_collect`:

```{python,eval=F}
from emodpy_malaria.reporters.builtin import *
add_report_node_demographics(task, manifest, 
                             IP_key_to_collect='StudyCohort')
```

### Report Event Recorder

To add an IP column to [`ReportEventRecorder`](https://docs.idmod.org/projects/emod-malaria/en/latest/software-report-event-recorder.html) that reports the IP value for each individual experiencing the requested events, use `ips_to_record`:

```{python, eval=F}
from emodpy_malaria.reporters.builtin import *
add_event_recorder(task, event_list=["NewClinicalCase","Received_Treatment"],
                     start_day=1, end_day=365, node_ids=[1], min_age_years=0,
                     max_age_years=100,
                     ips_to_record=['StudyCohort'])
```